# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
# Minuto 0 cada 2 horas como en el ejemplo 
 schedule:
  - cron: "* * * * *"  

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm run update-readme
    - uses: actions/checkout@v2
    - run: |  
        git config user.name vqc1909a
        git config user.email vqc1909a@gmail.com
        git add .
        git commit -m "[bot] Update README with latest info"
        git push origin main
